### PR TITLE
Scala constructor and method parsing

### PR DESCRIPTION
**Pull request by OndrejSpanel**
#### Description

Similar to Scala and Kotlin, this adds constructor and method parsing to Scala.

#### Screenshots (if appropriate):

image

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-Functional Change (non-user facing changes)

#### Checklist:

- [x] My code follows the code style of this project (`./gradlew check` passes clean).
    - Tip: If you have lint issues just run `./gradlew :ktlintMainSourceSetFormat`.
- [x] I updated the version.
- [x] I updated the changelog with the new functionality.

<sub> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

### CODE REVIEW

**Comment by OndrejSpanel** [comment]
@mallowigi I can add a Scala configuration like there already is for Java and Kotlin, but does it make sense, as it will be more or less another copy? Perhaps it would be better to merge the configuration for all those three languages into one?

**Comment by mallowigi** [comment]
If they are a carbon copy of the others, you can reuse the others

**Comment by OndrejSpanel** [comment]
What I mean is - do you want to have separate settings for Java / Kotlin / Scala, or should they be merged together? At the moment Kotlin and Java have separate settings, controlling the same functionality differently for different languages.

**Comment by mallowigi** [comment]
Yeah I can see from your PR. Ultimately we should use a different setting for this, but this would involve you to also touch the Configurable and State files.

**Comment by OndrejSpanel** [comment]
If you prefer that, I will do it that way.

**Comment by OndrejSpanel** [comment]
Separate Scala settings added

**Comment by mallowigi** [comment]
Thanks for your hard work. I will try to find some time in the weekend to check that nothing is broken with all these refactors

**Pull request merged**
